### PR TITLE
First run at the cache for the gogridengine

### PR DESCRIPTION
**Pull request by shairozan**
So here we have a Cache struct that's created and has its own sub processes and routines that handle everything. 

```
c := Cache{}
c.Initialize(3 * time.Seconds)
```

At this point, C is populated with a series of channels and contexts that manage a few goroutines. Access to the cache is handled by message request on a channel, and writes to it are handled by mutex lock operations. 

There's also a goroutine that will cycle every X duration (the one provided to initialize) and will get the up-to-date qstat output and put it onto the write channel.

### CODE REVIEW

**Comment by shairozan** [comment]
@dpastoor @bkyoung Do either of you have any issues with a managed cache structure like this? The proposed idea is that you're making requests to the Cache itself, but writes to it are automatically handled by a goroutine on a fixed schedule based on the duration provided during the Initialize method.

**Comment by shairozan** [comment]
Mutices proved wholly unecessary. Unbuffered channels worked fine

**Comment by dpastoor** [comment]
@shairozan IMO this needs some spec'ing before diving into the implementation. For example, how are we going to handle the concept of using qstat filters. If you get multiple (close) requests within the cache window but for different filters that aren't done on the go-side then how is that handled. 

In addition, the core implementation should probably use an existing cache library. No need to re-invent the wheel (if possible), _unless_ we can make an argument our needset is so minimal we don't need to pull something off. I am not sure where we're going to end up just yet, but tend towards thinking to leverage someone elses brain a bit.

I would consider using: https://github.com/dgraph-io/ristretto if it isn't too complex. Seems like it would be fine and dgraph has high engineering standards - https://blog.dgraph.io/post/caching-in-go/

**Comment by shairozan** [comment]
@dpastoor I'd updated the issue, but you're right. From a risk perspective it makes way more sense to just implement ristretto. Also mentioned why I think it makes sense to approach caching as a global go object instead of letting qstat handle it

**Pull request closed without merging**
